### PR TITLE
Request rework

### PR DESCRIPTION
**Pull request by CrimsonDart**
has untested, but theoretically perfectly functioning code
still needs saving and auto end feature on player quit
also trying to implement a Command framework, which the Request fw builds off of; 
instead of creating a new class for each command, just use the methods registerDeny(String command label), registerAccept(command label), and registerSend(command label)
arguments, executors and tabcompletes are already implemented for these commands.
more customization should also be implemented, however

### CODE REVIEW

**Comment by CrimsonDart** [comment]
also tried draft lol

**Comment by bkiscool** [comment]
Wait, why did you not merge

**Comment by CrimsonDart** [comment]
the branch was deleted
it mightve been because something weird happened with the merging process?

**Comment by bkiscool** [comment]
Okay, as long as the changes aren't lost

**Pull request closed without merging**
